### ISSUE TITLE
Bug v1.1.3 - Collection and Subcollenction with same name

### ISSUE THREAD

**Issue by maiconkf** [algolia/firestore-algolia-search#171]
I have these collections:
events
users > events

Algolia is getting the users/events instead of getting events

<img width="564" alt="image" src="https://github.com/algolia/firestore-algolia-search/assets/5395835/effc4bb5-add3-48f3-944f-54e5774b16c1">

Edit: This only occurs in existing records. New records do not experience this issue

**Comment by smomin-bd** [comment]
Can you provide step by step details when it works and when it doesn't work?

**Comment by guskuma** [comment]
This just happened with me too.

my collection path: 'customers/{uid}/referreds'
documents getting indexed from 'customers/{uid}/imports/{importid}/referreds'

I still didn't notice if it happens with new records but with existing it surely do.

**Comment by smomin** [comment]
unfortunately there is no api available to target a sub-collection.  in order to support sub-collections indexing, Firebase team recommended I use the collectionGroup api which grabs all collections with the collection name, e.g. `users`.  if Firebase team enables better targeting of subcollections, i will implement it.  for now, i am closing this since there is not an approach to resolve this issue.

**Comment by fringley** [comment]
Taking a look through the full indexing feature - it does appear that the collectionGroup search is used when the Collection Path doesn't begin with a `/`.

It would be helpful to update the documentation for the collection path to indicate that it will use a collectionGroup query if the Collection Path does not start with a slash.
