### ISSUE TITLE
Firestore document changes not reflected in algolia index

### ISSUE THREAD

**Issue by ktan185** [algolia/firestore-algolia-search#186]
Good day,

I've currently been using the extension for searching a the title of a video in my videos collection. When I set up the extension, I followed the tutorial found at [https://www.youtube.com/watch?v=9BCQHfacqNU](url) and It correctly indexed the current documents in my videos collections into my Algolia index, however whenever I update or add a new document, these changes are not reflected in my algolia index immediately. I have checked the logs for the executeIndexOperation and the function doesn't seem to be invoked either.

**Comment by smomin** [comment]
hey @ktan185 are you still running into this issue?  What version of the integration do you have?  Can you provide my the configuration details?  Have you used the Admin key to see if it resolves the issue?

**Comment by bleedweedsuz** [comment]
Same thing happed to me. After successfully installed the extension to firebase it copied all the documents to Algolia but after add, update, delete operation in firebase, it does not change anything in Algolia. I watched this tutorial because there is no new updated one. [Tutorial 1](https://www.youtube.com/watch?v=F9UMJaiuHtE).

I saw new thing in config like "Database ID" but i am using Firestore. So i just added my collection name as shown in the below image. Or do i have to use (default) here.
![Screenshot 2023-12-01 at 3 52 18 PM](https://github.com/algolia/firestore-algolia-search/assets/10117919/b3b619e2-6d99-4df4-8188-c58638e9ae7c)

**Comment by bleedweedsuz** [comment]
Solved: My problem was bad config:
in Database ID: (default) <---- [for more info](https://cloud.google.com/blog/products/databases/manage-multiple-firestore-databases-in-a-project)

**Comment by smomin** [comment]
is this issue resolved?

**Comment by ktan185** [comment]
@bleedweedsuz awesome thanks for this! worked for me too :)

@smomin yes the issue is resolved.
